# Generated by Django 5.2.7 on 2025-10-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('teacher_dash', '0007_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_lesson',
            field=models.ForeignKey(blank=True, help_text='Current lesson the user is on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_enrollments', to='teacher_dash.lesson'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Last time the user accessed this course', null=True),
        ),
    ]
