# Generated by Django 5.2.7 on 2025-10-12 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('teacher_dash', '0007_course_admin_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=255, unique=True)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paypal_response', models.JSONField(blank=True, help_text='Full PayPal API response', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='teacher_dash.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'), models.Index(fields=['course', '-created_at'], name='payments_course__1ead04_idx'), models.Index(fields=['paypal_order_id'], name='payments_paypal__8d2cd3_idx')],
            },
        ),
    ]
