# Generated by Django 5.2.7 on 2025-10-10 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0002_course_is_paid_course_is_submitted_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Expected duration in minutes', null=True),
        ),
    ]
