# Generated by Django 5.2.7 on 2025-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0003_lesson_created_at_alter_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_review_feedback',
            field=models.TextField(blank=True, help_text='Optional feedback from admin during course review', null=True),
        ),
    ]
