# Generated by Django 5.2.7 on 2025-10-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0006_alter_discussionpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_approved',
            field=models.BooleanField(default=False, help_text='Indicates if the course has been approved by an admin'),
        ),
    ]
