# Generated by Django 5.2.7 on 2025-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0007_course_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='iudchsicd', max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, default='iudchsicd', max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, default='iudchsicd', max_length=11, null=True, unique=True),
        ),
    ]
