# Generated by Django 5.2.7 on 2025-10-12 05:44

import teacher_dash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0008_course_slug_lesson_slug_module_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default=teacher_dash.models.gen_slug, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, default=teacher_dash.models.gen_slug, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, default=teacher_dash.models.gen_slug, max_length=11, null=True, unique=True),
        ),
    ]
