# Generated by Django 5.2.7 on 2025-10-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0009_alter_course_slug_alter_lesson_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
