# Generated by Django 5.2.7 on 2025-10-12 14:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0010_videolesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='admin_review_feedback',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional feedback from admin during course review', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='transcript',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
