# Generated by Django 5.2.7 on 2025-10-12 14:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0011_alter_bloglesson_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglesson',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='admin_review_feedback',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Admin Review Feedback'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='transcript',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Transcript'),
        ),
    ]
