# Generated by Django 5.2.7 on 2025-10-12 15:01

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0012_alter_bloglesson_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='teacher_dash.lesson')),
            ],
            options={
                'db_table': 'pdf_lessons',
            },
        ),
    ]
