# Generated by Django 5.2.7 on 2025-10-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0013_pdflesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('blog', 'Blog'), ('pdf', 'PDF')], max_length=10),
        ),
    ]
