# Generated by Django 5.2.7 on 2025-10-11 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('lms', '0001_initial'),
        ('teacher_dash', '0004_course_admin_review_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.IntegerField(default=0, help_text='Last watched position in seconds')),
                ('completed_percentage', models.IntegerField(default=0, help_text='Percentage of video watched (0-100)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='authentication.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='teacher_dash.lesson')),
            ],
            options={
                'db_table': 'video_progress',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
