# Generated by Django 5.2.7 on 2025-10-11 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0005_discussionpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionpost',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last edit', null=True),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Indicates if post was edited after creation'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned posts appear at the top'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='teacher_dash.discussionpost'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['course', '-created_at'], name='discussions_course__d984e0_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['parent_post'], name='discussions_parent__6c59a4_idx'),
        ),
    ]
