# Generated by Django 5.2.7 on 2025-10-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dash', '0006_alter_discussionpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', help_text='Course category', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0, help_text='Course credit hours or points'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Course difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed course description', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite requirements'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating (0-5)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to course thumbnail image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_url',
            field=models.URLField(blank=True, help_text='External content URL if applicable', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Lesson description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within module'),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within course'),
        ),
    ]
