# Generated by Django 5.2.7 on 2025-10-12 14:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='accessibility_needs',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Accessibility Needs'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_goals',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Learning Goals'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='special_needs',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Special Needs'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='credentials',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Credentials'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verification_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Verification Notes'),
        ),
    ]
