# Generated by Django 5.2.7 on 2025-10-12 14:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='accessibility_needs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Any accessibility requirements for learning'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Specific areas of interest for course recommendations'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='learning_goals',
            field=ckeditor.fields.RichTextField(blank=True, help_text='What the student hopes to learn/achieve'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='special_needs',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Special needs, conditions, or considerations for course recommendations'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Professional bio'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='credentials',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Professional credentials (degrees, certifications)'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='verification_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Admin notes about verification'),
        ),
    ]
