# Generated by Django 5.2.7 on 2025-10-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_studentprofile_accessibility_needs_and_more'),
        ('teacher_dash', '0014_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses bookmarked by the user', related_name='bookmarked_by', to='teacher_dash.course'),
        ),
    ]
