# Generated by Django 5.2.7 on 2025-10-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_bookmarked_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_courses',
        ),
    ]
